### ISSUE TITLE
Also useable for Android devices?

### ISSUE THREAD

**Issue by sk2212** [carlonluca/pi#58]
Amazing! It seems that it is possible to display 1080p videos on a Raspberry Pi.

So is there a possibility that the code of this project can be used to display HD content also on an Android device?

**Comment by carlonluca** [comment]
Qt already has a backend working on many Android devices.

**Comment by sk2212** [comment]
What? Can you please show me the QT backend which is able to play 1080p media files on an Android device?

**Comment by carlonluca** [comment]
The official Qt backend can assuming the device is powerful enough, which means most recent devices.

**Comment by atr0n** [comment]
Also, I remember there were some issues back on qt5.4. Video playback only worked via QtQuick and Video object. I don't know if they solved.
Anyway, qt5.7 looks promising for android since they are including material desing guideline and other stuff. Maybe they will improve qtmultimedia.

El 9 may. 2016 7:54 p. m., Luca Carlon <notifications@github.com> escribió:

The official Qt backend can assuming the device is powerful enough, which means most recent devices.
